# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Rpi-weather

# Short description (goes below the title; it will also be used in the RSS feed)
description: Instructions and support code for getting a cheap USB weather station connected to the Met Office <a href="http://wow.metoffice.gov.uk">wow.metoffice.gov.uk</a> using a Raspberry Pi.

# Your name, as you want it to appear underneath each post and in the footer
author: trastle

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://trastle.github.com/rpi-weather/

# Some more jeckyll settings under the hood
safe:        false
auto:        false